package com.example.foodalp.enums

enum class ListScreen {
    Launchview,
    Welcomeview,
    Registerview,
    Loginview,
    MenujuHomepage1View,
    MenujuHomepage2View,
    MenujuHomepage3View,
    AppDescView,
    HomePage,
    AddRestaurantView,
    AddRestaurantViewAdmin,
    UpdateProfileView,
    DetailProfileView,
    AdminPage,
    AddCityView,
    UpdateRestaurantView,
    CityDetailView,
    CityDetailViewAdmin,
    CityUDViewAdmin,
    AddReview,
    RestaurantDetailView,
    RestaurantDetailViewAdmin,
    UpdateReviewView,
    AddFoodView,
    FoodDetailViewAdmin,
    FoodDetailView
}