package com.example.foodalp.enums

enum class ListScreen {
    Launchview,
    Welcomeview,
    Registerview,
    Loginview,
    MenujuHomepage1View,
    MenujuHomepage2View,
    MenujuHomepage3View,
    AppDescView,
    HomePage,
    UpdateProfileView,
    DetailProfileView,
    AdminPage,
    AddRestaurantView,
    UpdateRestaurantView,
    AddCityView,
    CityDetailView,
    CityDetailViewAdmin,
    AddReview,
    RestaurantDetailView,
    UpdateReviewView,
    RestaurantDetailViewAdmin,
    AddRestaurantViewAdmin,
}